HW2 added
daniil-eshkin/first-term pull request #3
Opened 2020-06-29 21:36 UTC by daniil-eshkin

2020-07-04 17:58 UTC, kt-cpp requested changes
Я не уверен что я прям все косяки нашел, но есть что править

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.h
> +class big_integer {
![image](https://user-images.githubusercontent.com/67123994/86302285-a7993600-bc21-11ea-923d-3a75ff386db9.png)
[note]

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::big_integer(const big_integer &a) {
[semantic] member initializer list?

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer::big_integer(const big_integer &a) {
В других конструкторах тоже

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        if (!isalnum(s[i])) {
[semantic][note] Если определить это как UB, то ты уберешь ветвление и получишь больше скорости

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        *this += sign * (s[i] - '0');
[semantic] можно сначала все сложить а потом поменять знак унарным минусом - будет плюс скорость

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.h
> +    uint32_t further;
[note] странные лишние 4 байта которые можно вычислить на ходу, но править не обязательно

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t (*eval)(uint32_t, uint32_t, uint32_t&)) {
[design] `std::function`

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +big_integer &operator^=(big_integer &a, const big_integer &b) {
[design] не находишь все битовые операторы похожими?

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +uint32_t div_3_2(uint32_t a2, uint32_t a1, uint32_t a0, uint32_t b1, uint32_t b0) {
[note] без 128 типа, мужик, уважаю!

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    uint32_t (*eval)(uint32_t, uint32_t, uint32_t&)) {
Интересная функция кстати, странно что ты битовые так же не выразил

2020-07-04 17:58 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    while (a.digits.size() > 1 && a.digits.back() == a.further) {
[design] цикл столько раз повторяется в разных операциях, почему бы не вынести в функцию?

2020-07-05 12:13 UTC, kt-cpp requested changes

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        [](uint32_t a, uint32_t b) { return a ^ b; };
[note] [style] Зачем выносить это в отдельные static-переменные, если они используются по одному разу? Можно лямбды написать прямо в нужные операторы.

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +void trim(big_integer &a, size_t s) {
[style] Слово trim обозначает «обрезать». Ты точно это имел ввиду?

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        a.digits.push_back(a.further);
[minor] У вектора есть такой метод: `iterator insert( const_iterator pos, size_type count, const T& value );`

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    for (size_t i = std::max(a.digits.size(), b.digits.size()) - 1;; --i) {
[design] Можно сделать вот так:

```suggestion
    for (size_t i = std::max(a.digits.size(), b.digits.size()); i-- > 0;) {
```

И `if` не нужен.

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    digits.push_back(0);
`digits` тоже можно унести в список инициализации, даже короче получится. Аналогично ниже.

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    further = a.further;
??????

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    } else if (a.further > b.further) {
```
if (a.further != b.further) {
    return a.further < b.further;
}
```

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
См. замечание выше про `insert`.

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +        }
`erase`?

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
А если число `b` короче?

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    }
`insert(const_iterator pos, InputIt first, InputIt last)`

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.cpp
> +    return a -= (a / b) * b;
Ты в `unsigned_div` считаешь остаток. Почему бы не использовать его, и таким образом избавиться от умножения?

2020-07-05 12:13 UTC, kt-cpp commented on bigint/big_integer.h
> +#pragma once
[note] `#pragma once` не является частью стандарта

2020-07-05 12:50 UTC, daniil-eshkin commented on bigint/big_integer.cpp
> +    return a -= (a / b) * b;
Нет учета знаков, и в итоге из-за того, что числитель и знаментатель домножались на определенные константы, это число еще и не то, и все  равно должно пересчитываться.

2020-07-05 12:51 UTC, daniil-eshkin commented on bigint/big_integer.cpp
> +    }
См. big_integer::operator[].

2020-07-05 12:53 UTC, daniil-eshkin commented on bigint/big_integer.cpp
> +    }
Вектор будет переписан в следующем дз, а потому не хотел абьюзить слишком много его операций.

2020-07-05 12:53 UTC, daniil-eshkin commented on bigint/big_integer.cpp
> +        }
Вектор будет переписан в следующем дз, а потому не хотел абьюзить слишком много его операций.

2020-07-05 12:54 UTC, daniil-eshkin commented on bigint/big_integer.cpp
> +        a.digits.push_back(a.further);
Вектор будет переписан в следующем дз, а потому не хотел абьюзить слишком много его операций.

2020-07-06 18:46 UTC, kt-cpp requested changes
доделай некоторые миноры

2020-07-06 18:46 UTC, kt-cpp commented on bigint/big_integer.cpp
>  #include <stdexcept>
[note] зачем иклюды здесь, если есть хедер

2020-07-06 18:46 UTC, kt-cpp commented on bigint/big_integer.cpp
> +            a.further = 0;
присвоить можно и без else

2020-07-06 19:00 UTC, kt-cpp approved these changes

2020-07-06 19:00 UTC, merged